language: scala

os: linux

dist: xenial

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
    - travis_retry sbt compile scalafmt::test

scala:
  - 2.12.3
  - 2.11.8

# whitelist
branches:
  only:
    - master
